mqtt:
  hostname: 192.168.1.38
  port: 1883
  user: mqtt
  password: A8404880+a
device_name: Vero4K
client_id: osmc1
timezone: Europe/Moscow
update_interval: 300
manufacturer: Vero
model: Vero4K
logging_level: INFO