mqtt:
  hostname: 127.0.0.1
  port: 1883
  user:
  password:
device_name: device
client_id: client1
timezone: Europe/Moscow
update_interval: 300
manufacturer: manufacturer
model: model
logging_level: INFO
reboot/shutdown: False
log_file: log.txt